env: 
  es6: true
  node: true
  browser: true

extends:
  - eslint:recommended
  - plugin:vue/essential

parserOptions: 
  ecmaVersion: 2018

rules: 
  indent:
    - error
    - 2
  quotes:
    - warn
    - single
  semi:
    - error
    - never
  eqeqeq:
    - error
    - always
  no-console: off
